//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace humanrights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("humanrights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUMAN_RIGHTS.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Right.
        /// </summary>
        public static string humanRight {
            get {
                return ResourceManager.GetString("humanRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinds of Human Rights.
        /// </summary>
        public static string kinds {
            get {
                return ResourceManager.GetString("kinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTRODUCTION.
        /// </summary>
        public static string t_introduction {
            get {
                return ResourceManager.GetString("t_introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two kinds of Human Rights.
        /// </summary>
        public static string t_kinds {
            get {
                return ResourceManager.GetString("t_kinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        public static string t_quiz {
            get {
                return ResourceManager.GetString("t_quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of Human Rights.
        /// </summary>
        public static string t_types {
            get {
                return ResourceManager.GetString("t_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Declaration of Human Rights.
        /// </summary>
        public static string t_universaldeclaration {
            get {
                return ResourceManager.GetString("t_universaldeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUMAN RIGHTS.
        /// </summary>
        public static string t_welcome {
            get {
                return ResourceManager.GetString("t_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string types {
            get {
                return ResourceManager.GetString("types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Declaration.
        /// </summary>
        public static string universalDeclaration {
            get {
                return ResourceManager.GetString("universalDeclaration", resourceCulture);
            }
        }
    }
}
